### ISSUE TITLE
handle_wiki_read replaces old revisions

### ISSUE THREAD

**Issue by lisps** [turnermm/Updatable-Snippets-for-Dokuwiki#23]
i think replaceing the page content on IO_WIKIPAGE_READ is a bad idea.

it totally ignores revision handling.

**Comment by turnermm** [comment]
Submit a pull request

**Comment by turnermm** [comment]
See my revisions at https://github.com/turnermm/Updatable-Snippets-for-Dokuwiki/pull/26

**Comment by turnermm** [comment]
There is a new interface for handling Old Revisions.  While it retains the previous  ``old_revisions`` option, it adds an Old Revisions/Snippets interface to the Old Revisions listings page, where you can decide whether or not to insert  new snippets into an Old Revision.  This makes more sense than the previous process, since the user might want to recover the earlier page with the earlier snippet
