### ISSUE TITLE
pop-up window not working

### ISSUE THREAD

**Issue by meg3ve** [turnermm/Updatable-Snippets-for-Dokuwiki#4]
I just installed the Snippets Plugin. After making the snippets page with internal links, when I go to a new page and click on the snippets toolbar icon, a pop-up window appears that is not like the one demonstrated on the snippets plugin page (as shown below). There are now checkboxes or icons to click, and the links direct the window to the respective window. Let me know what I can do to resolve this issue. Thanks.

![snippets screenshot](https://cloud.githubusercontent.com/assets/9793683/8193134/fc92e9c8-1440-11e5-993f-646a3e6bd029.PNG)

**Comment by turnermm** [comment]
Correct.  That's not what you should be getting.  Try clearing out your browser cache and your Dokuwiki cache.  If necessary you can delete all directories from data/cache.

**Comment by meg3ve** [comment]
Thanks- I just cleared my browser and Dokuwiki cache but no luck. This pop-up window also appears on other people's computers as well when they go to edit pages, so I don't think it is a local problem just on my computer. Any other suggestions?

**Comment by turnermm** [comment]
Did you clear out the Dokuwiki cache?    In any event, I took over this plugin from an author who is no longer active on Dokuwiki.  My contribution has been the updatable features. However, you might try the original:
    https://github.com/cosmocode/dokuwiki-plugin-snippets/tarball/master
And you will find the original plugin page here:
   https://www.dokuwiki.org/plugin:snippets:original
I can't really help with this because I can't reproduce the error.  If the older version works and the updatable does not, then perhaps you can give me more details on the systems you are using.  When you say "other people's",  are you referring to your own office or other machines inside your own intranet?  What browsers are you using and on which desktops? What server are you running?  I can often test for most configurations.

**Comment by rnck** [comment]
@meg3ve Do you have the move plugin installed? If so, try to disable it and check if snippets plugin will work again.

See #5. There seem to be a bug.

**Comment by turnermm** [comment]
See my comment in https://github.com/turnermm/Updatable-Snippets-for-Dokuwiki/issues/5

**Comment by turnermm** [comment]
I've corrected the bug in the move plugin which corrupts the links in the snippets pop-up window.  Temporarily you can use the following url to get the corrected version but should check for updates from the  original author:
https://github.com/turnermm/dokuwiki-plugin-move.git
The small change I made should not affect the move plugin but it never hurts to test,

**Comment by turnermm** [comment]
There's a permanent fix now in the snippets plugin that works with the original move plugin.
