### ISSUE TITLE
Plugin conflict with move plugin

### ISSUE THREAD

**Issue by rnck** [turnermm/Updatable-Snippets-for-Dokuwiki#5]
Hi there,

it seems that your plugin doesn't work with the (new version) of the [move plugin](https://www.dokuwiki.org/plugin:move). Either this or the move plugin has a bug.

I couldn't find out where the problem is. Disabling the move plugin solves the problem, but is not an option for me.

Snippets popup looks like "normal" page, please see screenshot. Clicking on links opens page in the popup window and does not insert wiki source code to the editor.

![snippets_bug](https://cloud.githubusercontent.com/assets/165663/8301151/cec355b4-198b-11e5-9370-20152172c3d9.png)

Would be great if you can fix this, or someone point me into the right direction where to look for the bug.

Cheers
rnck

**Comment by turnermm** [comment]
I've tested with the original snippets plugin and the result is the same, which makes it possible to narrow down the conflict area,  In the code inherited from the original, the pop-up window creates its list of snippets from a standard DW page containing an unordered list of snippet pages.  The move plugin apparently takes over this unordered list and inserts it own values.  It also hides the icon for displaying the snippet in the right-hand panel of the snippets pop-up.

**Comment by turnermm** [comment]
I've posted an issue to t he move plugin.  You might want to do the same and explain what your problem is.

**Comment by rnck** [comment]
[Done](https://github.com/michitux/dokuwiki-plugin-move/issues/28#issuecomment-114978970). 

But I don't understand what possibly could affect the snippets popup page by the move plugin.

Cheers!

**Comment by turnermm** [comment]
The move plugin changes the link class required for the snippets links:
https://github.com/michitux/dokuwiki-plugin-move/issues/28#issuecomment-114978970

**Comment by turnermm** [comment]
You've found the answer.  It interferes with the functioning of the snippets plugin by changing the link class.

**Comment by turnermm** [comment]
I've done some checking of my own.  In firebug on my test, it's not just the change of class  but the fact that the move plugin strips out the icons which have clickable properties that implement the previewing and inserting.

**Comment by turnermm** [comment]
I've corrected the bug in the move plugin which corrupts the links in the snippets pop-up window.  Temporarily you can use the following url to get the corrected version but should check for updates from the  original author:
https://github.com/turnermm/dokuwiki-plugin-move.git
The small change I made should not affect the move plugin but it never hurts to test,

**Comment by michitux** [comment]
The move plugin does not strip anything, the move plugin just relies on `JSINFO` being set to be an object and gives an error otherwise which prevents any other JavaScript code from being executed. Actually other plugins like the `folded` plugin even rely on their properties being set. I can fix this in the move plugin (by applying the first commit of @turnermm) and also in the folded plugin but I'm wondering if it wouldn't make more sense to change the snippets plugin to properly populate `JSINFO`.

**Comment by turnermm** [comment]
I assumed that $JSINFO was always predefined with namespace and id, which were then converted to JSINFO.  I could easily enough enter a key into $JSINFO.  But that might not make a difference if my other concern is correct (https://github.com/michitux/dokuwiki-plugin-move/pull/31), so that the move code might be executed before the snippets code.  I will test your suggestion and see what happens.

**Comment by turnermm** [comment]
I've done as you suggest and all seems to be working.  I've pushed my revision to github.  
Thanks.

**Comment by turnermm** [comment]
It hadn't occurred to me that, as a pop-up window, it had no page and namespace to initialize $JSINFO.

**Comment by rnck** [comment]
I installed the update and can confirm it is working again now.

Thank you very much!
